version: '3'
services:
  bot:
    build: .
    container_name: scene_detector
    volumes:
      - .:/bot
      - /mnt/h/output:/videos
      - /mnt/h/output:/frames
      - /mnt/h/temp:/input
    tty: true